### ISSUE TITLE
Dataset Link not available

### ISSUE THREAD

**Issue by mhaut** [zjjerica/WHU-OHS-Pytorch#2]
Dear author,

Thank you very much for your interesting contribution. I am trying to download the dataset, but I am having issues: irsip.whu.edu.cn it tooks too long to respond (ERR_CONNECTION_TIMED_OUT). Please, could you please help me?

Thank you so much,
best regards.

**Comment by zjjerica** [comment]
Thank you for your support of our WHU-OHS dataset.
For other download link of WHU-OHS dataset, it can be downloaded in the zenodo website.(https://zenodo.org/record/7258035#.ZEOIaXZByUm)
Also, you can download the dataset in the following baidupan website within 30 days:
Website: https://pan.baidu.com/s/1CF8uqCNqlrend9Fjw9OXmw?pwd=klyp 
Extraction code: klyp

**Comment by mhaut** [comment]
thank you so much!
